# Generated by Django 3.2.9 on 2021-11-25 17:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('tiendafavorita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorita',
                'verbose_name_plural': 'tfavorita',
                'ordering': ['id'],
            },
        ),
    ]
